modLoader = "javafml"
loaderVersion = "[40,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/CorgiTaco/Mobifier/issues"
[[mods]]
modId = "mobifier"
version = "1.0.3"
displayName = "Mobifier"
displayURL = ""
logoFile = "assets/mobifier/mobifier.png"
credits = "J.T. McQuigg (JT122406)"
authors = "Corgi Taco"
description = '''
Edit and tweak mob loot tables + attributes.
'''
[[dependencies.mobifier]]
modId = "forge"
mandatory = true
versionRange = "[40.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mobifier]]
modId = "corgilib"
mandatory = true
versionRange = "[1.0.0.34,)"
ordering = "BEFORE"
side = "BOTH"