modLoader = "javafml"
loaderVersion = "[33,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/CorgiTaco/Mobifier/issues"
[[mods]]
modId = "mobifier"
version = "1.0"
displayName = "Mobifier"
displayURL = ""
logoFile = "icon.png"
credits = ""
authors = "Corgi Taco"
description = '''
Edit and tweak mob loot tables + attributes.
'''
[[dependencies.mobifier]]
modId = "forge"
mandatory = true
versionRange = "[33.0.0,)"
ordering = "NONE"
side = "BOTH"
